### ISSUE TITLE
proj_create: Error 1029 (File not found or invalid): pipeline: Pipeline: Bad step definition: proj=hgridshift (File not found or invalid)

### ISSUE THREAD

**Issue by swiss-knight** [opengisch/qgis-docker#78]
I'm trying to use opengisch Docker image for QGIS server (successfully serving some very simple PostGIS layers in `EPSG:2056`) but I'm facing this QGIS server error message when trying to create a new feature using WFS (from QGIS as a client):

```
...
my_app-qgis-1  | proj_create: Error 1029 (File not found or invalid): pipeline: Pipeline: Bad step definition: proj=hgridshift (File not found or invalid)
my_app-qgis-1  | 07:49:10 WARNING [13]: attr: name=Example_attribute idx=0 value=Test
```

At this stage I have to down and up the docker service again because it's totally frozen.

Is there anything I missed in the documentation?
How can I make it work with `EPSG:2056`? If possible of course.
It works well with WGS84 tables.

I'm using the `opengisch/qgis-server:3.30.2-jammy` image.

Here's the service definition in my Compose file:

```
qgis:
    image: opengisch/qgis-server:3.30.2-jammy
    environment:
      POSTGRES_USER:
      POSTGRES_PASSWORD:
      POSTGRES_HOST:
      POSTGRES_PORT:
      POSTGRES_DB:
      # Do not run the embedded copy of nginx
      SKIP_NGINX: "true"
      QGIS_SERVER_LOG_LEVEL: 0
      # Improve rendering performance
      QGIS_SERVER_PARALLEL_RENDERING: "true"
      QGIS_SERVER_MAX_THREADS: 4
      # Limit the maximum size returned by a GetMap
      QGIS_SERVER_WMS_MAX_HEIGHT: 5000
      QGIS_SERVER_WMS_MAX_WIDTH: 5000
    restart: "always"
    networks:
      - local_net
    depends_on:
      db:
        condition: service_healthy
    ports:
      - "9993:9993"
    volumes:
      - ./qgis/data:/io/data
      - ./qgis/pg_service.conf:/etc/postgresql-common/pg_service.conf:ro
```

I was hoping for an env var to make the project aware of other EPSG codes for example.

Thanks for your help and also for providing this nice Docker image.

Warm Regards.
